# len("Hello")


# print(type("Hello"))
# print(type(13))
# print(type(13.5))
# print(type(True))

print(int("123") + int("456"))
#forms of data type
# int()
# float()
# str()
# bool()


# print("Number of letters in your name: " + (len(input("Enter your name"))))


name_of_the_user = input("Enter your name")
length_of_name = len(name_of_the_user)

print(type("Number of letters in your name: "))#str
print(type(length_of_name))#int

print("Number of letters in your name: " + str(length_of_name))